// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jPcmxrZey5dugiqa2YSGj2OYvPjPkeE',
    appId: '1:98275117481:web:83209d46a33660f4915cb8',
    messagingSenderId: '98275117481',
    projectId: 'mzizi-app-technical-test',
    authDomain: 'mzizi-app-technical-test.firebaseapp.com',
    storageBucket: 'mzizi-app-technical-test.appspot.com',
    measurementId: 'G-M46M61T8VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtcAQWEs4SQQdkgJt0g0Id12MZfPkFZVc',
    appId: '1:98275117481:android:f44c6f0522474255915cb8',
    messagingSenderId: '98275117481',
    projectId: 'mzizi-app-technical-test',
    storageBucket: 'mzizi-app-technical-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQCrYTv_OF1hhK1lRgDgeN69FRB4iOkTU',
    appId: '1:98275117481:ios:602ae86944b58a2c915cb8',
    messagingSenderId: '98275117481',
    projectId: 'mzizi-app-technical-test',
    storageBucket: 'mzizi-app-technical-test.appspot.com',
    iosBundleId: 'com.example.technicalTestAppMzizi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQCrYTv_OF1hhK1lRgDgeN69FRB4iOkTU',
    appId: '1:98275117481:ios:602ae86944b58a2c915cb8',
    messagingSenderId: '98275117481',
    projectId: 'mzizi-app-technical-test',
    storageBucket: 'mzizi-app-technical-test.appspot.com',
    iosBundleId: 'com.example.technicalTestAppMzizi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7jPcmxrZey5dugiqa2YSGj2OYvPjPkeE',
    appId: '1:98275117481:web:5bd15370417c39c1915cb8',
    messagingSenderId: '98275117481',
    projectId: 'mzizi-app-technical-test',
    authDomain: 'mzizi-app-technical-test.firebaseapp.com',
    storageBucket: 'mzizi-app-technical-test.appspot.com',
    measurementId: 'G-BPTEZLBZZH',
  );

}